version: '3'
services:

  poll:
    build:
      context: ./poll
      dockerfile: "Dockerfile"
    ports:
      - "5000:80"
   

  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379"

  worker:
    build:
        context: ./worker
        dockerfile: "Dockerfile"

  db:
    image: "postgres:9.4"
    ports:
      - "6379"
    environment:
      - POSTGRES_PASSWORD=popeye